### PR TITLE
Upgrade `gardener` version `v1.6.5` to `v1.30.2`

### PR DESCRIPTION
**Pull request by AleksandarSavchev**
**What this PR does / why we need it**:
Vendor gardener `v1.30.2`. Unnecessary replace directives have been removed as well.

**Which issue(s) this PR fixes**:
Part of #63 

**Special notes for your reviewer**:

**Release note**:

```other operator
Dependency `github.com/gardener/gardener` is updated `v1.6.5` -> `v1.30.2`
```

### CODE REVIEW

**Review by himanshu-kun — CHANGES_REQUESTED** [review]
Hi @AleksandarSavchev 
thanks for the PR.
Wondering why not raise PR for the latest g/g release which is [`1.57.0`](https://github.com/gardener/gardener/releases/tag/v1.57.0) (actually `1.57.1` but thats released very recently)?

Also the build,test,check steps in the pipeline are failing with `vendor/k8s.io/client-go/discovery/discovery_client.go:30:2: cannot find package "." in:
	/tmp/build/a94a8fe5/pull-request-gardener.dependency-watchdog-pr.master/vendor/github.com/googleapis/gnostic/openapiv2`

this is a known issue , to resolve kindly follow this commits changes https://github.com/gardener/autoscaler/commit/3d258acf7ac4c7d92fc2a886e757a5ec2a82d74e

**Comment by ialidzhikov** [comment]
> Wondering why not raise PR for the latest g/g release which is [1.57.0](https://github.com/gardener/gardener/releases/tag/v1.57.0) (actually 1.57.1 but thats released very recently)?

@himanshu-kun , @AleksandarSavchev created https://github.com/gardener/dependency-watchdog/issues/63 and explained in the issue that in gardener/gardener@v1.31.0 a lot of generated clients/listers/informers are dropped and it is not trivial to update to gardener/gardener >= v1.31.0 -> you may need to refactor to use controller-runtime. Can you and your team take care for the updates >= v1.31.0? With this PR @AleksandarSavchev "helps" you by updating from v1.6.5 to v1.30.2.

**Comment by unmarshall** [comment]
@ialidzhikov We are mostly ready with the newer version of DWD which is going to use controller-runtime. We will merge soon. Till then this PR can provide would serve the intended purpose.

**Review by himanshu-kun — APPROVED** [review]
/lgtm

**Pull request merged**
