### PR TITLE
Fixed broken links - 2024.05

### PR DESCRIPTION
**Pull request by n-boshnakov**
**What this PR does / why we need it**:
This PR fixes broken links in the documentation.

/kind enhancement

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```doc developer
NONE
```

### CODE REVIEW

**Comment by n-boshnakov** [comment]
@ashwani2k @unmarshall Hello, could someone take a look at this PR?

**Review by unmarshall — APPROVED** [review]
/lgtm

**Comment by n-boshnakov** [comment]
@unmarshall Could you please merge this PR?

**Pull request merged**
