### PR TITLE
Fixed typo in log message

### PR DESCRIPTION
**Pull request by ScheererJ**
**What this PR does / why we need it**:
The pull request fixes a minor typo in the log message of the dependency watchdog probe code.

**Which issue(s) this PR fixes**:
None.

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by ashwani2k** [comment]
Thanks @ScheererJ  for the PR. 
We are in works to refactor the DWD as we were not happy with not just the way some of the terms are defined like `resultRun` which doesn't convey anything meaningful, but we also intend to make the behavior more deterministic as we observed with race conditions spurring with recently introduced secret rotation in gardener as well as handling of meltdown scenarios where it wasn't sure how long should one wait for a dependent component to scale down. 

@unmarshall  is currently in the process of publishing the new approach to the community which should be out soon. The implementation for the same is already underworks.  So i'll rather close this in lieu of overhauling,  wdyt?

@rishabh-11  may be you can run a spell-check on the new code base to verify if such typos still exist in the new codebase.

**Comment by unmarshall** [comment]
Yes i agree. We will double check all logs that DWD emits to ensure that it clearly depicts the message without spelling mistakes.
@ScheererJ i will publish the new approach soon. Implementation is also going at a good pace. Once we finish proper testing we will release the new version of DWD prober initially which will a lot of improvements. This is a very small change and if you still wish to merge this change i don't have any reasons to block it :)

**Comment by ScheererJ** [comment]
@ashwani2k & @unmarshall: Thanks for the heads-up. Feel free to close or merge this pull request at your convenience. It is certainly not very important, especially if the dependency watchdog is anyway rewritten.

**Pull request closed without merging**
